import React, { useEffect, useState } from "react";
import "./App.css";
import dayjs from "dayjs";
import { Button, Container, Grid, Pagination } from "@mui/material";
import { LocalizationProvider } from "@mui/x-date-pickers/LocalizationProvider";
import { AdapterDayjs } from "@mui/x-date-pickers/AdapterDayjs";
import { DateRangePicker } from "@mui/x-date-pickers-pro/DateRangePicker";
import { DemoItem } from "@mui/x-date-pickers/internals/demo";

import axios from "axios";
import {
  compareExpiredDates,
  compareStartDates,
  createData,
} from "./common/common.";
import Table from "@mui/material/Table";
import TableBody from "@mui/material/TableBody";
import TableCell from "@mui/material/TableCell";
import TableContainer from "@mui/material/TableContainer";
import TableHead from "@mui/material/TableHead";
import TableRow from "@mui/material/TableRow";
import Paper from "@mui/material/Paper";
import LoadingButton from "@mui/lab/LoadingButton";

function App() {
  const [value, setValue] = useState([
    {
      id: 1,
      name: "VINAYAKTEST",
      type: "percentage_discount",
      amount: "50.0000",
      min_purchase: "0.0000",
      expires: "Tue, 24 May 2022 18:30:00 +0000",
      enabled: false,
      code: "VINAYAKTESTPercentageOFF",
      applies_to: {
        entity: "categories",
        ids: [0, 81, 87, 100, 102, 103, 104, 105],
      },
      num_uses: 1,
      max_uses: 0,
      max_uses_per_customer: 0,
      restricted_to: [],
      shipping_methods: null,
      date_created: "Wed, 09 Jun 2021 11:36:38 +0000",
    },
    {
      id: 2,
      name: "testrsoff",
      type: "per_total_discount",
      amount: "300.0000",
      min_purchase: "10.0000",
      expires: "Tue, 24 May 2022 18:30:00 +0000",
      enabled: true,
      code: "testrsoff",
      applies_to: {
        entity: "categories",
        ids: [0],
      },
      num_uses: 2,
      max_uses: 0,
      max_uses_per_customer: 1,
      restricted_to: [],
      shipping_methods: null,
      date_created: "Wed, 09 Jun 2021 13:29:10 +0000",
    },
    {
      id: 3,
      name: "TESTORDERCOUPON",
      type: "percentage_discount",
      amount: "99.0000",
      min_purchase: "0.0000",
      expires: "Tue, 19 Apr 2022 18:30:00 +0000",
      enabled: true,
      code: "TESTORDERCOUPON",
      applies_to: {
        entity: "categories",
        ids: [0],
      },
      num_uses: 3,
      max_uses: 0,
      max_uses_per_customer: 0,
      restricted_to: [],
      shipping_methods: null,
      date_created: "Thu, 10 Jun 2021 09:55:39 +0000",
    },
    {
      id: 4,
      name: "5% OFF on Kapiva products",
      type: "percentage_discount",
      amount: "5.0000",
      min_purchase: "799.0000",
      expires: "Wed, 24 Dec 2025 18:30:00 +0000",
      enabled: false,
      code: "k",
      applies_to: {
        entity: "categories",
        ids: [0],
      },
      num_uses: 1103,
      max_uses: 0,
      max_uses_per_customer: 0,
      restricted_to: [],
      shipping_methods: null,
      date_created: "Wed, 16 Jun 2021 09:43:05 +0000",
    },
    {
      id: 6,
      name: "k5555",
      type: "percentage_discount",
      amount: "10.0000",
      min_purchase: "0.0000",
      expires: "",
      enabled: false,
      code: "k555",
      applies_to: {
        entity: "categories",
        ids: [0],
      },
      num_uses: 515,
      max_uses: 0,
      max_uses_per_customer: 0,
      restricted_to: [],
      shipping_methods: null,
      date_created: "Wed, 16 Jun 2021 12:14:39 +0000",
    },
    {
      id: 14,
      name: "Kapiva user testing code",
      type: "percentage_discount",
      amount: "90.0000",
      min_purchase: "0.0000",
      expires: "",
      enabled: false,
      code: "UAT90",
      applies_to: {
        entity: "categories",
        ids: [0, 102, 103, 104, 105, 139],
      },
      num_uses: 46,
      max_uses: 0,
      max_uses_per_customer: 0,
      restricted_to: [],
      shipping_methods: null,
      date_created: "Fri, 06 Aug 2021 13:26:55 +0000",
    },
    {
      id: 15,
      name: "KP:000001",
      type: "percentage_discount",
      amount: "1.0000",
      min_purchase: "0.0000",
      expires: "",
      enabled: false,
      code: "KPTEST",
      applies_to: {
        entity: "categories",
        ids: [85],
      },
      num_uses: 0,
      max_uses: 0,
      max_uses_per_customer: 1,
      restricted_to: [],
      shipping_methods: null,
      date_created: "Tue, 10 Aug 2021 11:14:03 +0000",
    },
    {
      id: 16,
      name: "KP:000002",
      type: "percentage_discount",
      amount: "1.0000",
      min_purchase: "0.0000",
      expires: "",
      enabled: false,
      code: "KPTEST2",
      applies_to: {
        entity: "categories",
        ids: [85],
      },
      num_uses: 0,
      max_uses: 0,
      max_uses_per_customer: 1,
      restricted_to: [],
      shipping_methods: null,
      date_created: "Tue, 10 Aug 2021 11:27:08 +0000",
    },
    {
      id: 17,
      name: "KAP313",
      type: "percentage_discount",
      amount: "15.0000",
      min_purchase: "0.0000",
      expires: "Sun, 22 Aug 2021 18:30:00 +0000",
      enabled: true,
      code: "tmpcoupon1",
      applies_to: {
        entity: "categories",
        ids: [0],
      },
      num_uses: 0,
      max_uses: 0,
      max_uses_per_customer: 0,
      restricted_to: [],
      shipping_methods: null,
      date_created: "Tue, 10 Aug 2021 11:45:58 +0000",
    },
    {
      id: 18,
      name: "RAKHI15",
      type: "percentage_discount",
      amount: "15.0000",
      min_purchase: "0.0000",
      expires: "Tue, 24 Aug 2021 18:30:00 +0000",
      enabled: true,
      code: "RAKHI15",
      applies_to: {
        entity: "categories",
        ids: [0],
      },
      num_uses: 2428,
      max_uses: 0,
      max_uses_per_customer: 0,
      restricted_to: [],
      shipping_methods: null,
      date_created: "Tue, 10 Aug 2021 12:57:12 +0000",
    },
    {
      id: 19,
      name: "k",
      type: "percentage_discount",
      amount: "10.0000",
      min_purchase: "1299.0000",
      expires: "Sun, 21 Dec 2025 18:30:00 +0000",
      enabled: false,
      code: "kp",
      applies_to: {
        entity: "categories",
        ids: [0],
      },
      num_uses: 649,
      max_uses: 0,
      max_uses_per_customer: 0,
      restricted_to: [],
      shipping_methods: null,
      date_created: "Tue, 10 Aug 2021 12:58:28 +0000",
    },
    {
      id: 20,
      name: "Test Razorpay Coupon",
      type: "per_total_discount",
      amount: "479.0000",
      min_purchase: "0.0000",
      expires: "",
      enabled: false,
      code: "TEST_RAZ",
      applies_to: {
        entity: "categories",
        ids: [88],
      },
      num_uses: 2,
      max_uses: 8,
      max_uses_per_customer: 0,
      restricted_to: [],
      shipping_methods: null,
      date_created: "Wed, 11 Aug 2021 09:43:07 +0000",
    },
    {
      id: 21,
      name: "KP_PAYTM_TEST",
      type: "percentage_discount",
      amount: "20.0000",
      min_purchase: "0.0000",
      expires: "Wed, 29 Sep 2021 18:30:00 +0000",
      enabled: true,
      code: "KP_PAYTM_TEST",
      applies_to: {
        entity: "categories",
        ids: [148],
      },
      num_uses: 0,
      max_uses: 0,
      max_uses_per_customer: 3,
      restricted_to: [],
      shipping_methods: null,
      date_created: "Thu, 12 Aug 2021 13:30:24 +0000",
    },
    {
      id: 22,
      name: "KP_PAYTM_TEST_API",
      type: "percentage_discount",
      amount: "20.0000",
      min_purchase: "0.0000",
      expires: "Wed, 29 Sep 2021 18:30:00 +0000",
      enabled: true,
      code: "KP_PAYTM_TEST_API",
      applies_to: {
        entity: "categories",
        ids: [148],
      },
      num_uses: 0,
      max_uses: 0,
      max_uses_per_customer: 3,
      restricted_to: [],
      shipping_methods: null,
      date_created: "Thu, 12 Aug 2021 13:41:03 +0000",
    },
    {
      id: 23,
      name: "KAPRPT25sFosaE",
      type: "percentage_discount",
      amount: "20.0000",
      min_purchase: "0.0000",
      expires: "Thu, 31 Mar 2022 18:30:00 +0000",
      enabled: true,
      code: "KAPRPT25sFosaE",
      applies_to: {
        entity: "categories",
        ids: [148],
      },
      num_uses: 0,
      max_uses: 0,
      max_uses_per_customer: 3,
      restricted_to: [],
      shipping_methods: null,
      date_created: "Thu, 12 Aug 2021 14:38:56 +0000",
    },
    {
      id: 24,
      name: "KAPRPT2PW2CPMS",
      type: "percentage_discount",
      amount: "20.0000",
      min_purchase: "0.0000",
      expires: "Thu, 31 Mar 2022 18:30:00 +0000",
      enabled: true,
      code: "KAPRPT2PW2CPMS",
      applies_to: {
        entity: "categories",
        ids: [148],
      },
      num_uses: 0,
      max_uses: 0,
      max_uses_per_customer: 3,
      restricted_to: [],
      shipping_methods: null,
      date_created: "Thu, 12 Aug 2021 14:38:56 +0000",
    },
    {
      id: 25,
      name: "KAPRPT2mexng7C",
      type: "percentage_discount",
      amount: "20.0000",
      min_purchase: "0.0000",
      expires: "Thu, 31 Mar 2022 18:30:00 +0000",
      enabled: true,
      code: "KAPRPT2mexng7C",
      applies_to: {
        entity: "categories",
        ids: [148],
      },
      num_uses: 0,
      max_uses: 0,
      max_uses_per_customer: 3,
      restricted_to: [],
      shipping_methods: null,
      date_created: "Thu, 12 Aug 2021 14:38:57 +0000",
    },
    {
      id: 26,
      name: "KAPRPT2aVW5xG1",
      type: "percentage_discount",
      amount: "20.0000",
      min_purchase: "0.0000",
      expires: "Thu, 31 Mar 2022 18:30:00 +0000",
      enabled: true,
      code: "KAPRPT2aVW5xG1",
      applies_to: {
        entity: "categories",
        ids: [148],
      },
      num_uses: 0,
      max_uses: 0,
      max_uses_per_customer: 3,
      restricted_to: [],
      shipping_methods: null,
      date_created: "Thu, 12 Aug 2021 14:38:57 +0000",
    },
    {
      id: 27,
      name: "KAPRPT2asTMTaT",
      type: "percentage_discount",
      amount: "20.0000",
      min_purchase: "0.0000",
      expires: "Thu, 31 Mar 2022 18:30:00 +0000",
      enabled: true,
      code: "KAPRPT2asTMTaT",
      applies_to: {
        entity: "categories",
        ids: [148],
      },
      num_uses: 0,
      max_uses: 0,
      max_uses_per_customer: 3,
      restricted_to: [],
      shipping_methods: null,
      date_created: "Thu, 12 Aug 2021 14:38:57 +0000",
    },
    {
      id: 28,
      name: "KAPRPT2rBwoav7",
      type: "percentage_discount",
      amount: "20.0000",
      min_purchase: "0.0000",
      expires: "Thu, 31 Mar 2022 18:30:00 +0000",
      enabled: true,
      code: "KAPRPT2rBwoav7",
      applies_to: {
        entity: "categories",
        ids: [148],
      },
      num_uses: 0,
      max_uses: 0,
      max_uses_per_customer: 3,
      restricted_to: [],
      shipping_methods: null,
      date_created: "Thu, 12 Aug 2021 14:38:58 +0000",
    },
    {
      id: 29,
      name: "KAPRPT2AuBczwq",
      type: "percentage_discount",
      amount: "20.0000",
      min_purchase: "0.0000",
      expires: "Thu, 31 Mar 2022 18:30:00 +0000",
      enabled: true,
      code: "KAPRPT2AuBczwq",
      applies_to: {
        entity: "categories",
        ids: [148],
      },
      num_uses: 0,
      max_uses: 0,
      max_uses_per_customer: 3,
      restricted_to: [],
      shipping_methods: null,
      date_created: "Thu, 12 Aug 2021 14:38:58 +0000",
    },
    {
      id: 30,
      name: "KAPRPT2OcVCLGe",
      type: "percentage_discount",
      amount: "20.0000",
      min_purchase: "0.0000",
      expires: "Thu, 31 Mar 2022 18:30:00 +0000",
      enabled: true,
      code: "KAPRPT2OcVCLGe",
      applies_to: {
        entity: "categories",
        ids: [148],
      },
      num_uses: 0,
      max_uses: 0,
      max_uses_per_customer: 3,
      restricted_to: [],
      shipping_methods: null,
      date_created: "Thu, 12 Aug 2021 14:38:59 +0000",
    },
    {
      id: 31,
      name: "KAPRPT2P4ifeCk",
      type: "percentage_discount",
      amount: "20.0000",
      min_purchase: "0.0000",
      expires: "Thu, 31 Mar 2022 18:30:00 +0000",
      enabled: true,
      code: "KAPRPT2P4ifeCk",
      applies_to: {
        entity: "categories",
        ids: [148],
      },
      num_uses: 0,
      max_uses: 0,
      max_uses_per_customer: 3,
      restricted_to: [],
      shipping_methods: null,
      date_created: "Thu, 12 Aug 2021 14:38:59 +0000",
    },
    {
      id: 32,
      name: "KAPRPT2RYJTbqT",
      type: "percentage_discount",
      amount: "20.0000",
      min_purchase: "0.0000",
      expires: "Thu, 31 Mar 2022 18:30:00 +0000",
      enabled: true,
      code: "KAPRPT2RYJTbqT",
      applies_to: {
        entity: "categories",
        ids: [148],
      },
      num_uses: 0,
      max_uses: 0,
      max_uses_per_customer: 3,
      restricted_to: [],
      shipping_methods: null,
      date_created: "Thu, 12 Aug 2021 14:38:59 +0000",
    },
    {
      id: 33,
      name: "KAPRPT2Q7y99Az",
      type: "percentage_discount",
      amount: "20.0000",
      min_purchase: "0.0000",
      expires: "Thu, 31 Mar 2022 18:30:00 +0000",
      enabled: true,
      code: "KAPRPT2Q7y99Az",
      applies_to: {
        entity: "categories",
        ids: [148],
      },
      num_uses: 0,
      max_uses: 0,
      max_uses_per_customer: 3,
      restricted_to: [],
      shipping_methods: null,
      date_created: "Thu, 12 Aug 2021 14:39:00 +0000",
    },
    {
      id: 34,
      name: "KAPRPT21hfp8X1",
      type: "percentage_discount",
      amount: "20.0000",
      min_purchase: "0.0000",
      expires: "Thu, 31 Mar 2022 18:30:00 +0000",
      enabled: true,
      code: "KAPRPT21hfp8X1",
      applies_to: {
        entity: "categories",
        ids: [148],
      },
      num_uses: 0,
      max_uses: 0,
      max_uses_per_customer: 3,
      restricted_to: [],
      shipping_methods: null,
      date_created: "Thu, 12 Aug 2021 14:39:00 +0000",
    },
    {
      id: 35,
      name: "KAPRPT2eCeBoKP",
      type: "percentage_discount",
      amount: "20.0000",
      min_purchase: "0.0000",
      expires: "Thu, 31 Mar 2022 18:30:00 +0000",
      enabled: true,
      code: "KAPRPT2eCeBoKP",
      applies_to: {
        entity: "categories",
        ids: [148],
      },
      num_uses: 0,
      max_uses: 0,
      max_uses_per_customer: 3,
      restricted_to: [],
      shipping_methods: null,
      date_created: "Thu, 12 Aug 2021 14:39:01 +0000",
    },
    {
      id: 36,
      name: "KAPRPT2hvyvA6h",
      type: "percentage_discount",
      amount: "20.0000",
      min_purchase: "0.0000",
      expires: "Thu, 31 Mar 2022 18:30:00 +0000",
      enabled: true,
      code: "KAPRPT2hvyvA6h",
      applies_to: {
        entity: "categories",
        ids: [148],
      },
      num_uses: 0,
      max_uses: 0,
      max_uses_per_customer: 3,
      restricted_to: [],
      shipping_methods: null,
      date_created: "Thu, 12 Aug 2021 14:39:01 +0000",
    },
    {
      id: 37,
      name: "KAPRPT2kOwn1Oc",
      type: "percentage_discount",
      amount: "20.0000",
      min_purchase: "0.0000",
      expires: "Thu, 31 Mar 2022 18:30:00 +0000",
      enabled: true,
      code: "KAPRPT2kOwn1Oc",
      applies_to: {
        entity: "categories",
        ids: [148],
      },
      num_uses: 0,
      max_uses: 0,
      max_uses_per_customer: 3,
      restricted_to: [],
      shipping_methods: null,
      date_created: "Thu, 12 Aug 2021 14:39:01 +0000",
    },
    {
      id: 38,
      name: "KAPRPT2xGCFGME",
      type: "percentage_discount",
      amount: "20.0000",
      min_purchase: "0.0000",
      expires: "Thu, 31 Mar 2022 18:30:00 +0000",
      enabled: true,
      code: "KAPRPT2xGCFGME",
      applies_to: {
        entity: "categories",
        ids: [148],
      },
      num_uses: 0,
      max_uses: 0,
      max_uses_per_customer: 3,
      restricted_to: [],
      shipping_methods: null,
      date_created: "Thu, 12 Aug 2021 14:39:02 +0000",
    },
    {
      id: 39,
      name: "KAPRPT22PoWPrk",
      type: "percentage_discount",
      amount: "20.0000",
      min_purchase: "0.0000",
      expires: "Thu, 31 Mar 2022 18:30:00 +0000",
      enabled: true,
      code: "KAPRPT22PoWPrk",
      applies_to: {
        entity: "categories",
        ids: [148],
      },
      num_uses: 0,
      max_uses: 0,
      max_uses_per_customer: 3,
      restricted_to: [],
      shipping_methods: null,
      date_created: "Thu, 12 Aug 2021 14:39:02 +0000",
    },
    {
      id: 40,
      name: "KAPRPT2AQUyVJq",
      type: "percentage_discount",
      amount: "20.0000",
      min_purchase: "0.0000",
      expires: "Thu, 31 Mar 2022 18:30:00 +0000",
      enabled: true,
      code: "KAPRPT2AQUyVJq",
      applies_to: {
        entity: "categories",
        ids: [148],
      },
      num_uses: 1,
      max_uses: 0,
      max_uses_per_customer: 3,
      restricted_to: [],
      shipping_methods: null,
      date_created: "Thu, 12 Aug 2021 14:39:03 +0000",
    },
    {
      id: 41,
      name: "KAPRPT2zDB25fu",
      type: "percentage_discount",
      amount: "20.0000",
      min_purchase: "0.0000",
      expires: "Thu, 31 Mar 2022 18:30:00 +0000",
      enabled: true,
      code: "KAPRPT2zDB25fu",
      applies_to: {
        entity: "categories",
        ids: [148],
      },
      num_uses: 0,
      max_uses: 0,
      max_uses_per_customer: 3,
      restricted_to: [],
      shipping_methods: null,
      date_created: "Thu, 12 Aug 2021 14:39:03 +0000",
    },
    {
      id: 42,
      name: "KAPRPT2apUeq4u",
      type: "percentage_discount",
      amount: "20.0000",
      min_purchase: "0.0000",
      expires: "Thu, 31 Mar 2022 18:30:00 +0000",
      enabled: true,
      code: "KAPRPT2apUeq4u",
      applies_to: {
        entity: "categories",
        ids: [148],
      },
      num_uses: 0,
      max_uses: 0,
      max_uses_per_customer: 3,
      restricted_to: [],
      shipping_methods: null,
      date_created: "Thu, 12 Aug 2021 14:39:03 +0000",
    },
    {
      id: 43,
      name: "KAPRPT2Dit8WWM",
      type: "percentage_discount",
      amount: "20.0000",
      min_purchase: "0.0000",
      expires: "Thu, 31 Mar 2022 18:30:00 +0000",
      enabled: true,
      code: "KAPRPT2Dit8WWM",
      applies_to: {
        entity: "categories",
        ids: [148],
      },
      num_uses: 0,
      max_uses: 0,
      max_uses_per_customer: 3,
      restricted_to: [],
      shipping_methods: null,
      date_created: "Thu, 12 Aug 2021 14:39:04 +0000",
    },
    {
      id: 44,
      name: "KAPRPT2qSroDSw",
      type: "percentage_discount",
      amount: "20.0000",
      min_purchase: "0.0000",
      expires: "Thu, 31 Mar 2022 18:30:00 +0000",
      enabled: true,
      code: "KAPRPT2qSroDSw",
      applies_to: {
        entity: "categories",
        ids: [148],
      },
      num_uses: 1,
      max_uses: 0,
      max_uses_per_customer: 3,
      restricted_to: [],
      shipping_methods: null,
      date_created: "Thu, 12 Aug 2021 14:39:04 +0000",
    },
    {
      id: 45,
      name: "KAPRPT2Wpie64x",
      type: "percentage_discount",
      amount: "20.0000",
      min_purchase: "0.0000",
      expires: "Thu, 31 Mar 2022 18:30:00 +0000",
      enabled: true,
      code: "KAPRPT2Wpie64x",
      applies_to: {
        entity: "categories",
        ids: [148],
      },
      num_uses: 0,
      max_uses: 0,
      max_uses_per_customer: 3,
      restricted_to: [],
      shipping_methods: null,
      date_created: "Thu, 12 Aug 2021 14:39:05 +0000",
    },
    {
      id: 46,
      name: "KAPRPT24uHvE8n",
      type: "percentage_discount",
      amount: "20.0000",
      min_purchase: "0.0000",
      expires: "Thu, 31 Mar 2022 18:30:00 +0000",
      enabled: true,
      code: "KAPRPT24uHvE8n",
      applies_to: {
        entity: "categories",
        ids: [148],
      },
      num_uses: 0,
      max_uses: 0,
      max_uses_per_customer: 3,
      restricted_to: [],
      shipping_methods: null,
      date_created: "Thu, 12 Aug 2021 14:39:05 +0000",
    },
    {
      id: 47,
      name: "KAPRPT2A4DOAmC",
      type: "percentage_discount",
      amount: "20.0000",
      min_purchase: "0.0000",
      expires: "Thu, 31 Mar 2022 18:30:00 +0000",
      enabled: true,
      code: "KAPRPT2A4DOAmC",
      applies_to: {
        entity: "categories",
        ids: [148],
      },
      num_uses: 0,
      max_uses: 0,
      max_uses_per_customer: 3,
      restricted_to: [],
      shipping_methods: null,
      date_created: "Thu, 12 Aug 2021 14:39:05 +0000",
    },
    {
      id: 48,
      name: "KAPRPT2WqyXaRF",
      type: "percentage_discount",
      amount: "20.0000",
      min_purchase: "0.0000",
      expires: "Thu, 31 Mar 2022 18:30:00 +0000",
      enabled: true,
      code: "KAPRPT2WqyXaRF",
      applies_to: {
        entity: "categories",
        ids: [148],
      },
      num_uses: 2,
      max_uses: 0,
      max_uses_per_customer: 3,
      restricted_to: [],
      shipping_methods: null,
      date_created: "Thu, 12 Aug 2021 14:39:06 +0000",
    },
    {
      id: 49,
      name: "KAPRPT2z2WQL3g",
      type: "percentage_discount",
      amount: "20.0000",
      min_purchase: "0.0000",
      expires: "Thu, 31 Mar 2022 18:30:00 +0000",
      enabled: true,
      code: "KAPRPT2z2WQL3g",
      applies_to: {
        entity: "categories",
        ids: [148],
      },
      num_uses: 0,
      max_uses: 0,
      max_uses_per_customer: 3,
      restricted_to: [],
      shipping_methods: null,
      date_created: "Thu, 12 Aug 2021 14:39:06 +0000",
    },
    {
      id: 50,
      name: "KAPRPT2NNhJOjV",
      type: "percentage_discount",
      amount: "20.0000",
      min_purchase: "0.0000",
      expires: "Thu, 31 Mar 2022 18:30:00 +0000",
      enabled: true,
      code: "KAPRPT2NNhJOjV",
      applies_to: {
        entity: "categories",
        ids: [148],
      },
      num_uses: 0,
      max_uses: 0,
      max_uses_per_customer: 3,
      restricted_to: [],
      shipping_methods: null,
      date_created: "Thu, 12 Aug 2021 14:39:07 +0000",
    },
    {
      id: 51,
      name: "KAPRPT24fajmQa",
      type: "percentage_discount",
      amount: "20.0000",
      min_purchase: "0.0000",
      expires: "Thu, 31 Mar 2022 18:30:00 +0000",
      enabled: true,
      code: "KAPRPT24fajmQa",
      applies_to: {
        entity: "categories",
        ids: [148],
      },
      num_uses: 0,
      max_uses: 0,
      max_uses_per_customer: 3,
      restricted_to: [],
      shipping_methods: null,
      date_created: "Thu, 12 Aug 2021 14:39:07 +0000",
    },
    {
      id: 52,
      name: "KAPRPT2ddaw5HT",
      type: "percentage_discount",
      amount: "20.0000",
      min_purchase: "0.0000",
      expires: "Thu, 31 Mar 2022 18:30:00 +0000",
      enabled: true,
      code: "KAPRPT2ddaw5HT",
      applies_to: {
        entity: "categories",
        ids: [148],
      },
      num_uses: 0,
      max_uses: 0,
      max_uses_per_customer: 3,
      restricted_to: [],
      shipping_methods: null,
      date_created: "Thu, 12 Aug 2021 14:39:08 +0000",
    },
    {
      id: 53,
      name: "KAPRPT26A4kem2",
      type: "percentage_discount",
      amount: "20.0000",
      min_purchase: "0.0000",
      expires: "Thu, 31 Mar 2022 18:30:00 +0000",
      enabled: true,
      code: "KAPRPT26A4kem2",
      applies_to: {
        entity: "categories",
        ids: [148],
      },
      num_uses: 0,
      max_uses: 0,
      max_uses_per_customer: 3,
      restricted_to: [],
      shipping_methods: null,
      date_created: "Thu, 12 Aug 2021 14:39:08 +0000",
    },
    {
      id: 54,
      name: "KAPRPT23g3a6Ms",
      type: "percentage_discount",
      amount: "20.0000",
      min_purchase: "0.0000",
      expires: "Thu, 31 Mar 2022 18:30:00 +0000",
      enabled: true,
      code: "KAPRPT23g3a6Ms",
      applies_to: {
        entity: "categories",
        ids: [148],
      },
      num_uses: 0,
      max_uses: 0,
      max_uses_per_customer: 3,
      restricted_to: [],
      shipping_methods: null,
      date_created: "Thu, 12 Aug 2021 14:39:08 +0000",
    },
    {
      id: 55,
      name: "KAPRPT28T9XbMU",
      type: "percentage_discount",
      amount: "20.0000",
      min_purchase: "0.0000",
      expires: "Thu, 31 Mar 2022 18:30:00 +0000",
      enabled: true,
      code: "KAPRPT28T9XbMU",
      applies_to: {
        entity: "categories",
        ids: [148],
      },
      num_uses: 0,
      max_uses: 0,
      max_uses_per_customer: 3,
      restricted_to: [],
      shipping_methods: null,
      date_created: "Thu, 12 Aug 2021 14:39:09 +0000",
    },
    {
      id: 56,
      name: "KAPRPT2qfq8Y1M",
      type: "percentage_discount",
      amount: "20.0000",
      min_purchase: "0.0000",
      expires: "Thu, 31 Mar 2022 18:30:00 +0000",
      enabled: true,
      code: "KAPRPT2qfq8Y1M",
      applies_to: {
        entity: "categories",
        ids: [148],
      },
      num_uses: 0,
      max_uses: 0,
      max_uses_per_customer: 3,
      restricted_to: [],
      shipping_methods: null,
      date_created: "Thu, 12 Aug 2021 14:39:09 +0000",
    },
    {
      id: 57,
      name: "KAPRPT2uVtOLof",
      type: "percentage_discount",
      amount: "20.0000",
      min_purchase: "0.0000",
      expires: "Thu, 31 Mar 2022 18:30:00 +0000",
      enabled: true,
      code: "KAPRPT2uVtOLof",
      applies_to: {
        entity: "categories",
        ids: [148],
      },
      num_uses: 0,
      max_uses: 0,
      max_uses_per_customer: 3,
      restricted_to: [],
      shipping_methods: null,
      date_created: "Thu, 12 Aug 2021 14:39:10 +0000",
    },
    {
      id: 58,
      name: "KAPRPT2ZM0cK27",
      type: "percentage_discount",
      amount: "20.0000",
      min_purchase: "0.0000",
      expires: "Thu, 31 Mar 2022 18:30:00 +0000",
      enabled: true,
      code: "KAPRPT2ZM0cK27",
      applies_to: {
        entity: "categories",
        ids: [148],
      },
      num_uses: 0,
      max_uses: 0,
      max_uses_per_customer: 3,
      restricted_to: [],
      shipping_methods: null,
      date_created: "Thu, 12 Aug 2021 14:39:10 +0000",
    },
    {
      id: 59,
      name: "KAPRPT2oyhFfd7",
      type: "percentage_discount",
      amount: "20.0000",
      min_purchase: "0.0000",
      expires: "Thu, 31 Mar 2022 18:30:00 +0000",
      enabled: true,
      code: "KAPRPT2oyhFfd7",
      applies_to: {
        entity: "categories",
        ids: [148],
      },
      num_uses: 0,
      max_uses: 0,
      max_uses_per_customer: 3,
      restricted_to: [],
      shipping_methods: null,
      date_created: "Thu, 12 Aug 2021 14:39:10 +0000",
    },
    {
      id: 60,
      name: "KAPRPT2FbVsPGf",
      type: "percentage_discount",
      amount: "20.0000",
      min_purchase: "0.0000",
      expires: "Thu, 31 Mar 2022 18:30:00 +0000",
      enabled: true,
      code: "KAPRPT2FbVsPGf",
      applies_to: {
        entity: "categories",
        ids: [148],
      },
      num_uses: 0,
      max_uses: 0,
      max_uses_per_customer: 3,
      restricted_to: [],
      shipping_methods: null,
      date_created: "Thu, 12 Aug 2021 14:39:11 +0000",
    },
    {
      id: 61,
      name: "KAPRPT2EyfVUQL",
      type: "percentage_discount",
      amount: "20.0000",
      min_purchase: "0.0000",
      expires: "Thu, 31 Mar 2022 18:30:00 +0000",
      enabled: true,
      code: "KAPRPT2EyfVUQL",
      applies_to: {
        entity: "categories",
        ids: [148],
      },
      num_uses: 0,
      max_uses: 0,
      max_uses_per_customer: 3,
      restricted_to: [],
      shipping_methods: null,
      date_created: "Thu, 12 Aug 2021 14:39:11 +0000",
    },
    {
      id: 62,
      name: "KAPRPT2y9Xet3t",
      type: "percentage_discount",
      amount: "20.0000",
      min_purchase: "0.0000",
      expires: "Thu, 31 Mar 2022 18:30:00 +0000",
      enabled: true,
      code: "KAPRPT2y9Xet3t",
      applies_to: {
        entity: "categories",
        ids: [148],
      },
      num_uses: 0,
      max_uses: 0,
      max_uses_per_customer: 3,
      restricted_to: [],
      shipping_methods: null,
      date_created: "Thu, 12 Aug 2021 14:39:12 +0000",
    },
    {
      id: 63,
      name: "KAPRPT2LrLhLeA",
      type: "percentage_discount",
      amount: "20.0000",
      min_purchase: "0.0000",
      expires: "Thu, 31 Mar 2022 18:30:00 +0000",
      enabled: true,
      code: "KAPRPT2LrLhLeA",
      applies_to: {
        entity: "categories",
        ids: [148],
      },
      num_uses: 0,
      max_uses: 0,
      max_uses_per_customer: 3,
      restricted_to: [],
      shipping_methods: null,
      date_created: "Thu, 12 Aug 2021 14:39:12 +0000",
    },
    {
      id: 64,
      name: "KAPRPT2XPcXEwA",
      type: "percentage_discount",
      amount: "20.0000",
      min_purchase: "0.0000",
      expires: "Thu, 31 Mar 2022 18:30:00 +0000",
      enabled: true,
      code: "KAPRPT2XPcXEwA",
      applies_to: {
        entity: "categories",
        ids: [148],
      },
      num_uses: 0,
      max_uses: 0,
      max_uses_per_customer: 3,
      restricted_to: [],
      shipping_methods: null,
      date_created: "Thu, 12 Aug 2021 14:39:12 +0000",
    },
    {
      id: 65,
      name: "KAPRPT2ZaZ4Ahs",
      type: "percentage_discount",
      amount: "20.0000",
      min_purchase: "0.0000",
      expires: "Thu, 31 Mar 2022 18:30:00 +0000",
      enabled: true,
      code: "KAPRPT2ZaZ4Ahs",
      applies_to: {
        entity: "categories",
        ids: [148],
      },
      num_uses: 0,
      max_uses: 0,
      max_uses_per_customer: 3,
      restricted_to: [],
      shipping_methods: null,
      date_created: "Thu, 12 Aug 2021 14:39:13 +0000",
    },
    {
      id: 66,
      name: "KAPRPT234jCTx8",
      type: "percentage_discount",
      amount: "20.0000",
      min_purchase: "0.0000",
      expires: "Thu, 31 Mar 2022 18:30:00 +0000",
      enabled: true,
      code: "KAPRPT234jCTx8",
      applies_to: {
        entity: "categories",
        ids: [148],
      },
      num_uses: 0,
      max_uses: 0,
      max_uses_per_customer: 3,
      restricted_to: [],
      shipping_methods: null,
      date_created: "Thu, 12 Aug 2021 14:39:13 +0000",
    },
    {
      id: 67,
      name: "KAPRPT2t0jtNEh",
      type: "percentage_discount",
      amount: "20.0000",
      min_purchase: "0.0000",
      expires: "Thu, 31 Mar 2022 18:30:00 +0000",
      enabled: true,
      code: "KAPRPT2t0jtNEh",
      applies_to: {
        entity: "categories",
        ids: [148],
      },
      num_uses: 0,
      max_uses: 0,
      max_uses_per_customer: 3,
      restricted_to: [],
      shipping_methods: null,
      date_created: "Thu, 12 Aug 2021 14:39:14 +0000",
    },
    {
      id: 68,
      name: "KAPRPT2NTbk03G",
      type: "percentage_discount",
      amount: "20.0000",
      min_purchase: "0.0000",
      expires: "Thu, 31 Mar 2022 18:30:00 +0000",
      enabled: true,
      code: "KAPRPT2NTbk03G",
      applies_to: {
        entity: "categories",
        ids: [148],
      },
      num_uses: 0,
      max_uses: 0,
      max_uses_per_customer: 3,
      restricted_to: [],
      shipping_methods: null,
      date_created: "Thu, 12 Aug 2021 14:39:14 +0000",
    },
    {
      id: 69,
      name: "KAPRPT2S9g2Bc4",
      type: "percentage_discount",
      amount: "20.0000",
      min_purchase: "0.0000",
      expires: "Thu, 31 Mar 2022 18:30:00 +0000",
      enabled: true,
      code: "KAPRPT2S9g2Bc4",
      applies_to: {
        entity: "categories",
        ids: [148],
      },
      num_uses: 0,
      max_uses: 0,
      max_uses_per_customer: 3,
      restricted_to: [],
      shipping_methods: null,
      date_created: "Thu, 12 Aug 2021 14:39:14 +0000",
    },
    {
      id: 70,
      name: "KAPRPT2D6wQC7r",
      type: "percentage_discount",
      amount: "20.0000",
      min_purchase: "0.0000",
      expires: "Thu, 31 Mar 2022 18:30:00 +0000",
      enabled: true,
      code: "KAPRPT2D6wQC7r",
      applies_to: {
        entity: "categories",
        ids: [148],
      },
      num_uses: 0,
      max_uses: 0,
      max_uses_per_customer: 3,
      restricted_to: [],
      shipping_methods: null,
      date_created: "Thu, 12 Aug 2021 14:39:15 +0000",
    },
    {
      id: 71,
      name: "KAPRPT2PqoSWKA",
      type: "percentage_discount",
      amount: "20.0000",
      min_purchase: "0.0000",
      expires: "Thu, 31 Mar 2022 18:30:00 +0000",
      enabled: true,
      code: "KAPRPT2PqoSWKA",
      applies_to: {
        entity: "categories",
        ids: [148],
      },
      num_uses: 0,
      max_uses: 0,
      max_uses_per_customer: 3,
      restricted_to: [],
      shipping_methods: null,
      date_created: "Thu, 12 Aug 2021 14:39:15 +0000",
    },
    {
      id: 72,
      name: "Influencer Coupon",
      type: "percentage_discount",
      amount: "15.0000",
      min_purchase: "0.0000",
      expires: "",
      enabled: true,
      code: "CI15",
      applies_to: {
        entity: "categories",
        ids: [0, 103, 104, 105, 139, 148],
      },
      num_uses: 3,
      max_uses: 0,
      max_uses_per_customer: 0,
      restricted_to: [],
      shipping_methods: null,
      date_created: "Thu, 12 Aug 2021 14:50:56 +0000",
    },
    {
      id: 73,
      name: "KAPRPT2Lq0tGBV",
      type: "percentage_discount",
      amount: "20.0000",
      min_purchase: "0.0000",
      expires: "Thu, 31 Mar 2022 18:30:00 +0000",
      enabled: true,
      code: "KAPRPT2Lq0tGBV",
      applies_to: {
        entity: "categories",
        ids: [148],
      },
      num_uses: 0,
      max_uses: 0,
      max_uses_per_customer: 3,
      restricted_to: [],
      shipping_methods: null,
      date_created: "Thu, 12 Aug 2021 15:19:33 +0000",
    },
    {
      id: 75,
      name: "a",
      type: "percentage_discount",
      amount: "15.0000",
      min_purchase: "0.0000",
      expires: "",
      enabled: true,
      code: "CIDJ15",
      applies_to: {
        entity: "categories",
        ids: [103, 104, 105, 139, 148],
      },
      num_uses: 0,
      max_uses: 0,
      max_uses_per_customer: 0,
      restricted_to: [],
      shipping_methods: null,
      date_created: "Thu, 12 Aug 2021 15:32:11 +0000",
    },
    {
      id: 76,
      name: "KAPRPT2gAn6YGp",
      type: "percentage_discount",
      amount: "20.0000",
      min_purchase: "0.0000",
      expires: "Thu, 31 Mar 2022 18:30:00 +0000",
      enabled: true,
      code: "KAPRPT2gAn6YGp",
      applies_to: {
        entity: "categories",
        ids: [148],
      },
      num_uses: 0,
      max_uses: 0,
      max_uses_per_customer: 3,
      restricted_to: [],
      shipping_methods: null,
      date_created: "Thu, 12 Aug 2021 16:01:30 +0000",
    },
    {
      id: 77,
      name: "KAPRPT2F9U9aEw",
      type: "percentage_discount",
      amount: "20.0000",
      min_purchase: "0.0000",
      expires: "Thu, 31 Mar 2022 18:30:00 +0000",
      enabled: true,
      code: "KAPRPT2F9U9aEw",
      applies_to: {
        entity: "categories",
        ids: [148],
      },
      num_uses: 0,
      max_uses: 0,
      max_uses_per_customer: 3,
      restricted_to: [],
      shipping_methods: null,
      date_created: "Thu, 12 Aug 2021 16:01:30 +0000",
    },
    {
      id: 78,
      name: "KAPRPT2vZJ0zfb",
      type: "percentage_discount",
      amount: "20.0000",
      min_purchase: "0.0000",
      expires: "Thu, 31 Mar 2022 18:30:00 +0000",
      enabled: true,
      code: "KAPRPT2vZJ0zfb",
      applies_to: {
        entity: "categories",
        ids: [148],
      },
      num_uses: 0,
      max_uses: 0,
      max_uses_per_customer: 3,
      restricted_to: [],
      shipping_methods: null,
      date_created: "Thu, 12 Aug 2021 16:01:30 +0000",
    },
    {
      id: 79,
      name: "KAPRPT2Y8yNwCW",
      type: "percentage_discount",
      amount: "20.0000",
      min_purchase: "0.0000",
      expires: "Thu, 31 Mar 2022 18:30:00 +0000",
      enabled: true,
      code: "KAPRPT2Y8yNwCW",
      applies_to: {
        entity: "categories",
        ids: [148],
      },
      num_uses: 1,
      max_uses: 0,
      max_uses_per_customer: 3,
      restricted_to: [],
      shipping_methods: null,
      date_created: "Thu, 12 Aug 2021 16:01:30 +0000",
    },
    {
      id: 80,
      name: "KAPRPT2w9q3ECm",
      type: "percentage_discount",
      amount: "20.0000",
      min_purchase: "0.0000",
      expires: "Thu, 31 Mar 2022 18:30:00 +0000",
      enabled: true,
      code: "KAPRPT2w9q3ECm",
      applies_to: {
        entity: "categories",
        ids: [148],
      },
      num_uses: 0,
      max_uses: 0,
      max_uses_per_customer: 3,
      restricted_to: [],
      shipping_methods: null,
      date_created: "Thu, 12 Aug 2021 16:01:30 +0000",
    },
    {
      id: 81,
      name: "KAPRPT2gaFGqc4",
      type: "percentage_discount",
      amount: "20.0000",
      min_purchase: "0.0000",
      expires: "Thu, 31 Mar 2022 18:30:00 +0000",
      enabled: true,
      code: "KAPRPT2gaFGqc4",
      applies_to: {
        entity: "categories",
        ids: [148],
      },
      num_uses: 0,
      max_uses: 0,
      max_uses_per_customer: 3,
      restricted_to: [],
      shipping_methods: null,
      date_created: "Thu, 12 Aug 2021 16:01:30 +0000",
    },
    {
      id: 82,
      name: "KAPRPT2XVGWfBz",
      type: "percentage_discount",
      amount: "20.0000",
      min_purchase: "0.0000",
      expires: "Thu, 31 Mar 2022 18:30:00 +0000",
      enabled: true,
      code: "KAPRPT2XVGWfBz",
      applies_to: {
        entity: "categories",
        ids: [148],
      },
      num_uses: 0,
      max_uses: 0,
      max_uses_per_customer: 3,
      restricted_to: [],
      shipping_methods: null,
      date_created: "Thu, 12 Aug 2021 16:01:30 +0000",
    },
    {
      id: 83,
      name: "KAPRPT2pzBkaDm",
      type: "percentage_discount",
      amount: "20.0000",
      min_purchase: "0.0000",
      expires: "Thu, 31 Mar 2022 18:30:00 +0000",
      enabled: true,
      code: "KAPRPT2pzBkaDm",
      applies_to: {
        entity: "categories",
        ids: [148],
      },
      num_uses: 0,
      max_uses: 0,
      max_uses_per_customer: 3,
      restricted_to: [],
      shipping_methods: null,
      date_created: "Thu, 12 Aug 2021 16:01:30 +0000",
    },
    {
      id: 84,
      name: "KAPRPT2vYPCkeC",
      type: "percentage_discount",
      amount: "20.0000",
      min_purchase: "0.0000",
      expires: "Thu, 31 Mar 2022 18:30:00 +0000",
      enabled: true,
      code: "KAPRPT2vYPCkeC",
      applies_to: {
        entity: "categories",
        ids: [148],
      },
      num_uses: 0,
      max_uses: 0,
      max_uses_per_customer: 3,
      restricted_to: [],
      shipping_methods: null,
      date_created: "Thu, 12 Aug 2021 16:01:30 +0000",
    },
    {
      id: 85,
      name: "KAPRPT2FCvVE5o",
      type: "percentage_discount",
      amount: "20.0000",
      min_purchase: "0.0000",
      expires: "Thu, 31 Mar 2022 18:30:00 +0000",
      enabled: true,
      code: "KAPRPT2FCvVE5o",
      applies_to: {
        entity: "categories",
        ids: [148],
      },
      num_uses: 0,
      max_uses: 0,
      max_uses_per_customer: 3,
      restricted_to: [],
      shipping_methods: null,
      date_created: "Thu, 12 Aug 2021 16:01:31 +0000",
    },
    {
      id: 86,
      name: "KAPRPT2tbtyUn6",
      type: "percentage_discount",
      amount: "20.0000",
      min_purchase: "0.0000",
      expires: "Thu, 31 Mar 2022 18:30:00 +0000",
      enabled: true,
      code: "KAPRPT2tbtyUn6",
      applies_to: {
        entity: "categories",
        ids: [148],
      },
      num_uses: 0,
      max_uses: 0,
      max_uses_per_customer: 3,
      restricted_to: [],
      shipping_methods: null,
      date_created: "Thu, 12 Aug 2021 16:01:31 +0000",
    },
    {
      id: 87,
      name: "KAPRPT2ddEi813",
      type: "percentage_discount",
      amount: "20.0000",
      min_purchase: "0.0000",
      expires: "Thu, 31 Mar 2022 18:30:00 +0000",
      enabled: true,
      code: "KAPRPT2ddEi813",
      applies_to: {
        entity: "categories",
        ids: [148],
      },
      num_uses: 0,
      max_uses: 0,
      max_uses_per_customer: 3,
      restricted_to: [],
      shipping_methods: null,
      date_created: "Thu, 12 Aug 2021 16:01:31 +0000",
    },
    {
      id: 88,
      name: "KAPRPT2DjMaGRD",
      type: "percentage_discount",
      amount: "20.0000",
      min_purchase: "0.0000",
      expires: "Thu, 31 Mar 2022 18:30:00 +0000",
      enabled: true,
      code: "KAPRPT2DjMaGRD",
      applies_to: {
        entity: "categories",
        ids: [148],
      },
      num_uses: 0,
      max_uses: 0,
      max_uses_per_customer: 3,
      restricted_to: [],
      shipping_methods: null,
      date_created: "Thu, 12 Aug 2021 16:01:31 +0000",
    },
    {
      id: 89,
      name: "KAPRPT2z08G8je",
      type: "percentage_discount",
      amount: "20.0000",
      min_purchase: "0.0000",
      expires: "Thu, 31 Mar 2022 18:30:00 +0000",
      enabled: true,
      code: "KAPRPT2z08G8je",
      applies_to: {
        entity: "categories",
        ids: [148],
      },
      num_uses: 0,
      max_uses: 0,
      max_uses_per_customer: 3,
      restricted_to: [],
      shipping_methods: null,
      date_created: "Thu, 12 Aug 2021 16:01:31 +0000",
    },
    {
      id: 90,
      name: "KAPRPT2ZfESygf",
      type: "percentage_discount",
      amount: "20.0000",
      min_purchase: "0.0000",
      expires: "Thu, 31 Mar 2022 18:30:00 +0000",
      enabled: true,
      code: "KAPRPT2ZfESygf",
      applies_to: {
        entity: "categories",
        ids: [148],
      },
      num_uses: 1,
      max_uses: 0,
      max_uses_per_customer: 3,
      restricted_to: [],
      shipping_methods: null,
      date_created: "Thu, 12 Aug 2021 16:01:31 +0000",
    },
    {
      id: 91,
      name: "KAPRPT2YxhWc0m",
      type: "percentage_discount",
      amount: "20.0000",
      min_purchase: "0.0000",
      expires: "Thu, 31 Mar 2022 18:30:00 +0000",
      enabled: true,
      code: "KAPRPT2YxhWc0m",
      applies_to: {
        entity: "categories",
        ids: [148],
      },
      num_uses: 0,
      max_uses: 0,
      max_uses_per_customer: 3,
      restricted_to: [],
      shipping_methods: null,
      date_created: "Thu, 12 Aug 2021 16:01:31 +0000",
    },
    {
      id: 92,
      name: "KAPRPT2tfLsiwf",
      type: "percentage_discount",
      amount: "20.0000",
      min_purchase: "0.0000",
      expires: "Thu, 31 Mar 2022 18:30:00 +0000",
      enabled: true,
      code: "KAPRPT2tfLsiwf",
      applies_to: {
        entity: "categories",
        ids: [148],
      },
      num_uses: 0,
      max_uses: 0,
      max_uses_per_customer: 3,
      restricted_to: [],
      shipping_methods: null,
      date_created: "Thu, 12 Aug 2021 16:01:31 +0000",
    },
    {
      id: 93,
      name: "KAPRPT2b07rQrx",
      type: "percentage_discount",
      amount: "20.0000",
      min_purchase: "0.0000",
      expires: "Thu, 31 Mar 2022 18:30:00 +0000",
      enabled: true,
      code: "KAPRPT2b07rQrx",
      applies_to: {
        entity: "categories",
        ids: [148],
      },
      num_uses: 0,
      max_uses: 0,
      max_uses_per_customer: 3,
      restricted_to: [],
      shipping_methods: null,
      date_created: "Thu, 12 Aug 2021 16:01:31 +0000",
    },
    {
      id: 94,
      name: "KAPRPT2G5bVYvP",
      type: "percentage_discount",
      amount: "20.0000",
      min_purchase: "0.0000",
      expires: "Thu, 31 Mar 2022 18:30:00 +0000",
      enabled: true,
      code: "KAPRPT2G5bVYvP",
      applies_to: {
        entity: "categories",
        ids: [148],
      },
      num_uses: 1,
      max_uses: 0,
      max_uses_per_customer: 3,
      restricted_to: [],
      shipping_methods: null,
      date_created: "Thu, 12 Aug 2021 16:01:31 +0000",
    },
    {
      id: 95,
      name: "KAPRPT2LLZMAWO",
      type: "percentage_discount",
      amount: "20.0000",
      min_purchase: "0.0000",
      expires: "Thu, 31 Mar 2022 18:30:00 +0000",
      enabled: true,
      code: "KAPRPT2LLZMAWO",
      applies_to: {
        entity: "categories",
        ids: [148],
      },
      num_uses: 0,
      max_uses: 0,
      max_uses_per_customer: 3,
      restricted_to: [],
      shipping_methods: null,
      date_created: "Thu, 12 Aug 2021 16:01:31 +0000",
    },
    {
      id: 96,
      name: "KAPRPT2qXfEr1Q",
      type: "percentage_discount",
      amount: "20.0000",
      min_purchase: "0.0000",
      expires: "Thu, 31 Mar 2022 18:30:00 +0000",
      enabled: true,
      code: "KAPRPT2qXfEr1Q",
      applies_to: {
        entity: "categories",
        ids: [148],
      },
      num_uses: 0,
      max_uses: 0,
      max_uses_per_customer: 3,
      restricted_to: [],
      shipping_methods: null,
      date_created: "Thu, 12 Aug 2021 16:01:31 +0000",
    },
    {
      id: 97,
      name: "KAPRPT2akENwrK",
      type: "percentage_discount",
      amount: "20.0000",
      min_purchase: "0.0000",
      expires: "Thu, 31 Mar 2022 18:30:00 +0000",
      enabled: true,
      code: "KAPRPT2akENwrK",
      applies_to: {
        entity: "categories",
        ids: [148],
      },
      num_uses: 0,
      max_uses: 0,
      max_uses_per_customer: 3,
      restricted_to: [],
      shipping_methods: null,
      date_created: "Thu, 12 Aug 2021 16:01:31 +0000",
    },
    {
      id: 98,
      name: "KAPRPT2aP9z4y5",
      type: "percentage_discount",
      amount: "20.0000",
      min_purchase: "0.0000",
      expires: "Thu, 31 Mar 2022 18:30:00 +0000",
      enabled: true,
      code: "KAPRPT2aP9z4y5",
      applies_to: {
        entity: "categories",
        ids: [148],
      },
      num_uses: 1,
      max_uses: 0,
      max_uses_per_customer: 3,
      restricted_to: [],
      shipping_methods: null,
      date_created: "Thu, 12 Aug 2021 16:01:31 +0000",
    },
    {
      id: 99,
      name: "KAPRPT2859xvYZ",
      type: "percentage_discount",
      amount: "20.0000",
      min_purchase: "0.0000",
      expires: "Thu, 31 Mar 2022 18:30:00 +0000",
      enabled: true,
      code: "KAPRPT2859xvYZ",
      applies_to: {
        entity: "categories",
        ids: [148],
      },
      num_uses: 0,
      max_uses: 0,
      max_uses_per_customer: 3,
      restricted_to: [],
      shipping_methods: null,
      date_created: "Thu, 12 Aug 2021 16:01:31 +0000",
    },
    {
      id: 100,
      name: "KAPRPT2pWtppgs",
      type: "percentage_discount",
      amount: "20.0000",
      min_purchase: "0.0000",
      expires: "Thu, 31 Mar 2022 18:30:00 +0000",
      enabled: true,
      code: "KAPRPT2pWtppgs",
      applies_to: {
        entity: "categories",
        ids: [148],
      },
      num_uses: 0,
      max_uses: 0,
      max_uses_per_customer: 3,
      restricted_to: [],
      shipping_methods: null,
      date_created: "Thu, 12 Aug 2021 16:01:31 +0000",
    },
    {
      id: 101,
      name: "KAPRPT2UjROx7f",
      type: "percentage_discount",
      amount: "20.0000",
      min_purchase: "0.0000",
      expires: "Thu, 31 Mar 2022 18:30:00 +0000",
      enabled: true,
      code: "KAPRPT2UjROx7f",
      applies_to: {
        entity: "categories",
        ids: [148],
      },
      num_uses: 0,
      max_uses: 0,
      max_uses_per_customer: 3,
      restricted_to: [],
      shipping_methods: null,
      date_created: "Thu, 12 Aug 2021 16:01:31 +0000",
    },
    {
      id: 102,
      name: "KAPRPT2XdNJK77",
      type: "percentage_discount",
      amount: "20.0000",
      min_purchase: "0.0000",
      expires: "Thu, 31 Mar 2022 18:30:00 +0000",
      enabled: true,
      code: "KAPRPT2XdNJK77",
      applies_to: {
        entity: "categories",
        ids: [148],
      },
      num_uses: 0,
      max_uses: 0,
      max_uses_per_customer: 3,
      restricted_to: [],
      shipping_methods: null,
      date_created: "Thu, 12 Aug 2021 16:01:31 +0000",
    },
    {
      id: 103,
      name: "KAPRPT2YAgKGRe",
      type: "percentage_discount",
      amount: "20.0000",
      min_purchase: "0.0000",
      expires: "Thu, 31 Mar 2022 18:30:00 +0000",
      enabled: true,
      code: "KAPRPT2YAgKGRe",
      applies_to: {
        entity: "categories",
        ids: [148],
      },
      num_uses: 0,
      max_uses: 0,
      max_uses_per_customer: 3,
      restricted_to: [],
      shipping_methods: null,
      date_created: "Thu, 12 Aug 2021 16:01:31 +0000",
    },
    {
      id: 104,
      name: "KAPRPT2yU7UGdx",
      type: "percentage_discount",
      amount: "20.0000",
      min_purchase: "0.0000",
      expires: "Thu, 31 Mar 2022 18:30:00 +0000",
      enabled: true,
      code: "KAPRPT2yU7UGdx",
      applies_to: {
        entity: "categories",
        ids: [148],
      },
      num_uses: 0,
      max_uses: 0,
      max_uses_per_customer: 3,
      restricted_to: [],
      shipping_methods: null,
      date_created: "Thu, 12 Aug 2021 16:01:31 +0000",
    },
    {
      id: 105,
      name: "KAPRPT27Uhegd0",
      type: "percentage_discount",
      amount: "20.0000",
      min_purchase: "0.0000",
      expires: "Thu, 31 Mar 2022 18:30:00 +0000",
      enabled: true,
      code: "KAPRPT27Uhegd0",
      applies_to: {
        entity: "categories",
        ids: [148],
      },
      num_uses: 0,
      max_uses: 0,
      max_uses_per_customer: 3,
      restricted_to: [],
      shipping_methods: null,
      date_created: "Thu, 12 Aug 2021 16:01:31 +0000",
    },
    {
      id: 106,
      name: "KAPRPT233wNg1b",
      type: "percentage_discount",
      amount: "20.0000",
      min_purchase: "0.0000",
      expires: "Thu, 31 Mar 2022 18:30:00 +0000",
      enabled: true,
      code: "KAPRPT233wNg1b",
      applies_to: {
        entity: "categories",
        ids: [148],
      },
      num_uses: 0,
      max_uses: 0,
      max_uses_per_customer: 3,
      restricted_to: [],
      shipping_methods: null,
      date_created: "Thu, 12 Aug 2021 16:01:31 +0000",
    },
    {
      id: 107,
      name: "KAPRPT2631mAym",
      type: "percentage_discount",
      amount: "20.0000",
      min_purchase: "0.0000",
      expires: "Thu, 31 Mar 2022 18:30:00 +0000",
      enabled: true,
      code: "KAPRPT2631mAym",
      applies_to: {
        entity: "categories",
        ids: [148],
      },
      num_uses: 0,
      max_uses: 0,
      max_uses_per_customer: 3,
      restricted_to: [],
      shipping_methods: null,
      date_created: "Thu, 12 Aug 2021 16:01:31 +0000",
    },
    {
      id: 108,
      name: "KAPRPT2pU0CPiV",
      type: "percentage_discount",
      amount: "20.0000",
      min_purchase: "0.0000",
      expires: "Thu, 31 Mar 2022 18:30:00 +0000",
      enabled: true,
      code: "KAPRPT2pU0CPiV",
      applies_to: {
        entity: "categories",
        ids: [148],
      },
      num_uses: 0,
      max_uses: 0,
      max_uses_per_customer: 3,
      restricted_to: [],
      shipping_methods: null,
      date_created: "Thu, 12 Aug 2021 16:01:31 +0000",
    },
    {
      id: 109,
      name: "KAPRPT2G61o8TR",
      type: "percentage_discount",
      amount: "20.0000",
      min_purchase: "0.0000",
      expires: "Thu, 31 Mar 2022 18:30:00 +0000",
      enabled: true,
      code: "KAPRPT2G61o8TR",
      applies_to: {
        entity: "categories",
        ids: [148],
      },
      num_uses: 0,
      max_uses: 0,
      max_uses_per_customer: 3,
      restricted_to: [],
      shipping_methods: null,
      date_created: "Thu, 12 Aug 2021 16:01:31 +0000",
    },
  ]);
  const [showTable, setShowTable] = useState(false);
  const [startdate, setStartdate] = useState(new Date());
  const [expireData, setExpireData] = useState(new Date());
  const [loading, setLoading] = useState(false);
  const [rows, setRows] = useState([]);
  let coupons = [];
  let page = 1;

  const getFilteredCoupons = () => {
    console.log("Adasdasdasdas", value.length);
    setRows([]);

    console.log("dfdsfsdfsd", rows);

    for (let index = 0; index < value.length; index++) {
      setRows((rows) => [
        ...rows,
        createData(
          value[index].id,
          value[index].code,
          value[index].name,
          value[index].amount,
          value[index].date_created,
          value[index].expires
        ),
      ]);
    }
    console.log(rows);
    setLoading(rows ? false : true);
  };

  useEffect(() => {
    axios(`https://api.bigcommerce.com/stores/5h8rqg02f8/v2/coupons`, {
      method: "GET",
      headers: {
        "X-Auth-Token": "ddm1fct3nofvzvhwqlxq48qv2cnlns1",
        "Content-Type": "application/json",
      },
    }).then(function (resp) {
      let data = resp.data;
      if (data !== "") {
        console.log("brfore loop");
        for (let i = 0; i < data.length; i++) {
          console.log("enter loop");
          if (data[i].expires !== "") {
            if (
              startdate !== ""
                ? compareStartDates(data[i].expires, startdate) &&
                  compareExpiredDates(data[i].expires, expireData)
                : compareExpiredDates(data[i].expires, expireData)
            ) {
              // console.log(data[1]);
              coupons.push(data[i]);
            }
          } else {
            console.log(data[i]);
          }
        }
        page = page + 1;
        data = [];
        // res = await get_coupon(page, storeHash, authToken);
      } else {
        setValue(coupons);
      }
    });
  }, []);

  return (
    <div className="App">
      <Container maxWidth="xl" style={{ textAlign: "center" }}>
        <h1>Coupon</h1>
        <Grid container spacing={2}>
          <Grid xs={4} style={{ alignSelf: "baseline" }}>
            <h2>Select Date</h2>
          </Grid>
          <Grid xs={6}>
            <LocalizationProvider dateAdapter={AdapterDayjs}>
              <DemoItem component="DateRangePicker">
                <DateRangePicker
                  defaultValue={[dayjs("2022-04-17"), dayjs("2022-04-21")]}
                  className="calendar"
                  onChange={(e) => (
                    setStartdate(e[0].$d), setExpireData(e[1].$d)
                  )}
                />
              </DemoItem>
            </LocalizationProvider>
          </Grid>
        </Grid>
        <LoadingButton
          size="small"
          loading={loading}
          variant="contained"
          onClick={() => getFilteredCoupons()}
          disabled={loading}
          style={{ marginTop: "1%", marginBottom: "1%" }}
        >
          <span>disabled</span>
        </LoadingButton>
        {rows && rows.length !== 0 ? (
          <Container maxWidth="100%" style={{ marginBottom: "2%" }}>
            <TableContainer component={Paper}>
              <Table sx={{ minWidth: "100%" }} aria-label="simple table">
                <TableHead>
                  {/* {value && value.mpa} */}
                  <TableRow>
                    <TableCell align="center">id</TableCell>
                    <TableCell align="center">code</TableCell>
                    <TableCell align="center">name</TableCell>
                    <TableCell align="center">amount</TableCell>
                    <TableCell align="center">date_created</TableCell>
                    <TableCell align="center">expires</TableCell>
                  </TableRow>
                </TableHead>
                <TableBody>
                  {rows.slice(0, 10).map((row) => (
                    <TableRow
                      key={row.id}
                      sx={{
                        "&:last-child td, &:last-child th": { border: 0 },
                      }}
                    >
                      <TableCell align="center">{row.id}</TableCell>
                      <TableCell component="th" scope="row">
                        {row.code}
                      </TableCell>
                      <TableCell align="center">{row.name}</TableCell>
                      <TableCell align="center">{row.amount}</TableCell>
                      <TableCell align="center">{row.date_created}</TableCell>
                      <TableCell align="center">{row.expires}</TableCell>
                    </TableRow>
                  ))}
                </TableBody>
                <Pagination
                  count={10}
                  color="primary"
                  style={{ marginTop: "1%", marginBottom: "1%" }}
                />
              </Table>
            </TableContainer>
          </Container>
        ) : (
          ""
        )}
      </Container>
    </div>
  );
}

export default App;
